student={
    "name":"neha",
    "score":{
        "chem":98,
        "phy":97,
        "math":99
        }    
        }
print(student)
print(student["score"])
print(student["score"]["math"])
